### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by POSTiGA1** [HyukIsBack/simple-cloudflare-flooder#1]
Hello Sir

i get bellow error:

Traceback (most recent call last):
  File "flooder.py", line 32, in <module>
    LaunchCFB(target, thread, t)
  File "flooder.py", line 8, in LaunchCFB
    scraper = cloudscraper.create_scraper()
  File "/usr/local/lib/python3.6/site-packages/cloudscraper/__init__.py", line 317, in create_scraper
    scraper = cls(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/cloudscraper/__init__.py", line 171, in __init__
    ssl_context=self.ssl_context
  File "/usr/local/lib/python3.6/site-packages/cloudscraper/__init__.py", line 77, in __init__
    self.ssl_context.orig_wrap_socket = self.ssl_context.wrap_socket
AttributeError: 'SSLContext' object has no attribute 'orig_wrap_socket'

**Comment by HyukIsBack** [comment]
use [karma ddos ](https://github.com/HyukIsBack/KARMA-DDoS)
